<a href="https://colab.research.google.com/github/zaoul/zaoul.github.io/blob/master/leetcode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#数组数组

## 找出数组中重复的数字
在一个长度为 n 的数组 nums 里的所有数字都在 0～n-1 的范围内。数组中某些数字是重复的，但不知道有几个数字重复了，也不知道每个数字重复了几次。请找出数组中任意一个重复的数字。
运行时间/内存消耗
法1：遍历。4936ms/19MB
法2：

In [ ]:
nums=[2, 3, 1, 0, 2, 5, 3]
copy = []
for num in nums:
  if num not in copy:
    copy.append(num)
  else:
    print(num)
    break

2


## 二维数组中的查找
在一个 n * m 的二维数组中，每一行都按照从左到右递增的顺序排序，每一列都按照从上到下递增的顺序排序。请完成一个高效的函数，输入这样的一个二维数组和一个整数，判断数组中是否含有该整数。


In [ ]:
import numpy as np
matrix=[[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]]
target = 20
matrix = np.array(matrix)
m,n=matrix.shape
while m > 0 and n > 0:
  if target == matrix[0][n-1]:
    print(True)
    break
  elif target > matrix[0][n-1]:
    matrix = matrix[1:,:]
    m = m - 1
  else:
    matrix = matrix[:,:-1]
    n = n - 1
    print(matrix, n)
print(False)

[[ 3  6  9 16]
 [10 13 14 17]
 [18 21 23 26]] 4
[[18 21 23]] 3
[[18 21]] 2
[[18]] 1
False


In [ ]:
matrix=[]
matrix = np.array(matrix)
m,n=matrix.shape 

ValueError: ignored

# 字符串

## 替换空格
请实现一个函数，把字符串 s 中的每个空格替换成"%20"。

In [ ]:
s = "We are happy."
s=s.replace(' ', '%20')
print(s)

We%20are%20happy.


# 链表

## 旋转链表

In [ ]:
class Solution:
    def rotateRight(self, head: ListNode, k: int) -> ListNode:
        if not head or not head.next:
            return head
        
        a = head
        kk = 0
        while a.next:
            k += 1
            a = a.next
        if kk + 1 >= k:
            k = k % (kk+1)
        
        a.next = head
        b = head
        for kk in range(k):
            b = b.next
        return b


# 栈

## 逆波兰表达式求值

根据 逆波兰表示法，求表达式的值。
有效的算符包括 +、-、*、/ 。每个运算对象可以是整数，也可以是另一个逆波兰表达式。

说明：
整数除法只保留整数部分。
给定逆波兰表达式总是有效的。换句话说，表达式总会得出有效数值且不存在除数为0的情况。
 


In [ ]:
tokens = ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]
stack=[]
for i in tokens:
  if i not in '+-*/':
    stack.append(int(i))
  else:
    v1 = stack.pop(-1)
    v2 = stack.pop(-1)
    if i == '+':
        count = v2 + v1
    elif i == '-':
        count = v2 - v1
    elif i == '*':
        count = v2 * v1
    elif i == '/':
        count = int(v2 / v1)
    stack.append(count)
print(stack[0])

22


In [ ]:
flowerbed = [1,0,0,0,1,0,0]
n=2
m = 0
count = 0
num = 0
flag1 = 0
flag2 = 0
if flowerbed[0] == 0:
    flag1 = 1
if flowerbed[-1] == 0:
    flag2 = 1
if flowerbed == [0] or flowerbed == [0,0]:
    print(True) 
for f in flowerbed:
    if f == 0:
        m += 1
        if m % 2 == 1 and m > 1:
            num = m // 2
        elif m % 2 == 0 and m > 1 and flag1 == 1 :
            flag1 = 0
            num = m // 2 
        elif m % 2 == 0 and m > 1:
            num = m // 2 - 1
        else:
            num = 0
    else:
        m = 0
        count += num
        num = 0
if flowerbed[-1] == 0 :
    count += num
if m % 2 == 0 and m > 1 and flag2 ==1:
    count += 1

if count >= n:
    print(True)
else:
    print(False)

True
